from tkinter import *
a=Tk()
a.title('Giao dien')
a.geometry('300x300')
b=Label(a,text="Hello world")
b.place(x=30,y=110)
def dip():
    x=Tk()
    x.title("Ung dung")
    x.geometry('300x300')
    y=Label(x,text="Welcome")
    y.pack()
    z=Button(x,text="Thoat",command=quit)
    z.place(x=250,y=250)
c=Button(a,text="OK",command=dip)
c.place(x=140,y=150)
def let():
    m=Tk()
    m.title("Khong")
    m.geometry('300x300')
    n=Label(m,text="Chac chan?")
    n.place(x=130,y=130)
    o=Button(m,text="Sure",command=quit)
    o.place(x=150,y=150)
d=Button(a,text="Ve",command=let)
d.place(x=140,y=170)
